<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Juan Pérez',
                'email' => 'juan.perez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 1,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'María González',
                'email' => 'maria.gonzalez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 2,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Carlos Rodríguez',
                'email' => 'carlos.rodriguez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 3,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ana Martínez',
                'email' => 'ana.martinez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 4,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Luis Fernández',
                'email' => 'luis.fernandez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 5,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ana Gómez',
                'email' => 'ana.gomez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 6,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Carlos Pérez',
                'email' => 'carlos.perez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 7,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'María López',
                'email' => 'maria.lopez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 8,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Jorge Ramírez',
                'email' => 'jorge.ramirez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 9,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Santiago López',
                'email' => 'santiago.lopez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 10,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Valeria Torres',
                'email' => 'valeria.torres@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 11,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Emiliano Díaz',
                'email' => 'emiliano.diaz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 12,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Luciana Castro',
                'email' => 'luciana.castro@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 13,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Matías García',
                'email' => 'matias.garcia@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 14,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Camila Hernández',
                'email' => 'camila.hernandez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 15,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Diego Vargas',
                'email' => 'diego.vargas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 16,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Sofía Morales',
                'email' => 'sofia.morales@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 17,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Andrés Flores',
                'email' => 'andres.flores@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 18,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 3,
            ],
            //Another seeders
            [
                'name' => 'Andrés Ortiz',
                'email' => 'andres.ortiz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 20,
                'identificadorGrupoEmpre' => 7,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Patricia Silva',
                'email' => 'patricia.silva@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 21,
                'identificadorGrupoEmpre' => 7,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Roberto Mendoza',
                'email' => 'roberto.mendoza@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 22,
                'identificadorGrupoEmpre' => 7,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Gabriela Romero',
                'email' => 'gabriela.romero@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 23,
                'identificadorGrupoEmpre' => 7,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Francisco Iglesias',
                'email' => 'francisco.iglesias@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 24,
                'identificadorGrupoEmpre' => 7,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Marta Cabrera',
                'email' => 'marta.cabrera@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 25,
                'identificadorGrupoEmpre' => 8,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Alberto Rojas',
                'email' => 'alberto.rojas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 26,
                'identificadorGrupoEmpre' => 8,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Cristina Flores',
                'email' => 'cristina.flores@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 27,
                'identificadorGrupoEmpre' => 8,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Jorge Castillo',
                'email' => 'jorge.castillo@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 28,
                'identificadorGrupoEmpre' => 8,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Natalia Soto',
                'email' => 'natalia.soto@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 29,
                'identificadorGrupoEmpre' => 8,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Raúl Paredes',
                'email' => 'raul.paredes@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 30,
                'identificadorGrupoEmpre' => 9,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Adriana Campos',
                'email' => 'adriana.campos@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 31,
                'identificadorGrupoEmpre' => 9,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Enrique Vargas',
                'email' => 'enrique.vargas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 32,
                'identificadorGrupoEmpre' => 9,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Lorena Peña',
                'email' => 'lorena.pena@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 33,
                'identificadorGrupoEmpre' => 9,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Sergio Guerrero',
                'email' => 'sergio.guerrero@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 34,
                'identificadorGrupoEmpre' => 9,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Valeria Méndez',
                'email' => 'valeria.mendez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 35,
                'identificadorGrupoEmpre' => 10,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Héctor Cruz',
                'email' => 'hector.cruz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 36,
                'identificadorGrupoEmpre' => 10,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Alicia Reyes',
                'email' => 'alicia.reyes@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 37,
                'identificadorGrupoEmpre' => 10,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Gustavo Herrera',
                'email' => 'gustavo.herrera@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 38,
                'identificadorGrupoEmpre' => 10,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Claudia Aguilar',
                'email' => 'claudia.aguilar@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 39,
                'identificadorGrupoEmpre' => 10,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Eduardo Salazar',
                'email' => 'eduardo.salazar@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 40,
                'identificadorGrupoEmpre' => 11,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Rosa Rivas',
                'email' => 'rosa.rivas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 41,
                'identificadorGrupoEmpre' => 11,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Manuel Guzmán',
                'email' => 'manuel.guzman@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 42,
                'identificadorGrupoEmpre' => 11,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Teresa Muñoz',
                'email' => 'teresa.munoz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 43,
                'identificadorGrupoEmpre' => 11,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ángel Ponce',
                'email' => 'angel.ponce@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 44,
                'identificadorGrupoEmpre' => 11,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Silvia Delgado',
                'email' => 'silvia.delgado@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 45,
                'identificadorGrupoEmpre' => 12,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ramón Morales',
                'email' => 'ramon.morales@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 46,
                'identificadorGrupoEmpre' => 12,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Julia Ortega',
                'email' => 'julia.ortega@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 47,
                'identificadorGrupoEmpre' => 12,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Tomás Vargas',
                'email' => 'tomas.vargas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 48,
                'identificadorGrupoEmpre' => 12,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Beatriz Serrano',
                'email' => 'beatriz.serrano@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 49,
                'identificadorGrupoEmpre' => 12,
                'identificadorRol' => 3,
            ],
        ]);
    }
}
