<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Juan Pérez',
                'email' => 'juan.perez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 1,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'María González',
                'email' => 'maria.gonzalez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 2,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Carlos Rodríguez',
                'email' => 'carlos.rodriguez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 3,
                'identificadorGrupoEmpre' => 1,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ana Martínez',
                'email' => 'ana.martinez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 4,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Luis Fernández',
                'email' => 'luis.fernandez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 5,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Ana Gómez',
                'email' => 'ana.gomez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 6,
                'identificadorGrupoEmpre' => 2,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Carlos Pérez',
                'email' => 'carlos.perez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 7,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'María López',
                'email' => 'maria.lopez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 8,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Jorge Ramírez',
                'email' => 'jorge.ramirez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 9,
                'identificadorGrupoEmpre' => 3,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Santiago López',
                'email' => 'santiago.lopez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 10,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Valeria Torres',
                'email' => 'valeria.torres@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 11,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Emiliano Díaz',
                'email' => 'emiliano.diaz@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 12,
                'identificadorGrupoEmpre' => 4,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Luciana Castro',
                'email' => 'luciana.castro@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 13,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Matías García',
                'email' => 'matias.garcia@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 14,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Camila Hernández',
                'email' => 'camila.hernandez@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 15,
                'identificadorGrupoEmpre' => 5,
                'identificadorRol' => 3,
            ],
            [
                'name' => 'Diego Vargas',
                'email' => 'diego.vargas@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 16,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 1,
            ],
            [
                'name' => 'Sofía Morales',
                'email' => 'sofia.morales@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 17,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 2,
            ],
            [
                'name' => 'Andrés Flores',
                'email' => 'andres.flores@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'identificadorPerso' => 18,
                'identificadorGrupoEmpre' => 6,
                'identificadorRol' => 3,
            ],

        ]);
    }
}
